---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  roles_path: roles
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_chef_for_busser: false
  playbook: main.yml

platforms:
  - name: centos-7.2

verifier:
  name: inspec
  sudo_path: true

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
