name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - actions-test

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/setup-ruby@v1
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello

      # Install Ruby gems
      - name: Install Ruby gems
        run: |
          gem install kitchen-ansible
          gem install kitchen-vargrant
          gem install kitchen-inspec
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'